// flow-typed signature: 8d8d020a65ecde33868fa008b0c0bf28
// flow-typed version: <<STUB>>/errno_v^0.1.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'errno'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'errno' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'errno/build' {
  declare module.exports: any;
}

declare module 'errno/cli' {
  declare module.exports: any;
}

declare module 'errno/custom' {
  declare module.exports: any;
}

declare module 'errno/errno' {
  declare module.exports: any;
}

declare module 'errno/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'errno/build.js' {
  declare module.exports: $Exports<'errno/build'>;
}
declare module 'errno/cli.js' {
  declare module.exports: $Exports<'errno/cli'>;
}
declare module 'errno/custom.js' {
  declare module.exports: $Exports<'errno/custom'>;
}
declare module 'errno/errno.js' {
  declare module.exports: $Exports<'errno/errno'>;
}
declare module 'errno/test.js' {
  declare module.exports: $Exports<'errno/test'>;
}
