// flow-typed signature: 8d628f7d410305b5eb8726121c06fb3f
// flow-typed version: <<STUB>>/@mattstyles/alias_v^1.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mattstyles/alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mattstyles/alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mattstyles/alias/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mattstyles/alias/index' {
  declare module.exports: $Exports<'@mattstyles/alias'>;
}
declare module '@mattstyles/alias/index.js' {
  declare module.exports: $Exports<'@mattstyles/alias'>;
}
declare module '@mattstyles/alias/test.js' {
  declare module.exports: $Exports<'@mattstyles/alias/test'>;
}
